# Stata parity harness: golden locations, fixtures, and comparators
# (IMPLEMENTATION_PLAN.md §5). Goldens are generated by qa/make_golden.R and
# committed under tests/testthat/golden/, so these tests never need Stata.
#
# Each comparator has a pure core (golden_compare_*) that returns a data
# frame of mismatches, and an expect_* wrapper that fails with the first few.
# test-golden-harness.R feeds every core deliberately broken input.

# Highest implementation phase whose golden scenarios must pass. Scenarios
# from later phases are skipped with skip("Phase N"). Raise this as phases land.
# One gate for both commands (table1_tc scenarios are phases 2-3, regtab
# phases 4-5): every scenario runs. (Phase 4 landed on its own branch
# before Phase 3 merged, with a separate regtab gate; the gates were merged
# when both branches reached main. Phase 5 ran as branches phase5a and
# phase5b with per-branch golden_done_phase5a/b lists, folded in here when
# they were integrated on branch phase5. Phase 7 (puttab/stacktab 7a,
# stratetab 7b, effecttab 7d) did the same with golden_done_phase7a/b/d,
# folded in at the Phase 7 integration: there are no Phase 6 scenarios, and
# every phase-7 scenario in the manifest must pass.)
golden_phase_done <- 7L

# Scenarios of a later phase that already pass, un-skipped individually while
# a phase is split across parallel branches. Each branch defines its own
# `golden_done_<branch>` character vector of scenario ids in its own
# helper-golden-done-<branch>.R file, so branches never edit the same line;
# fold them into golden_phase_done (and delete the files) once the phase lands.
golden_done_ids <- function() {
  env <- parent.env(environment())  # where the helper files were sourced
  nms <- ls(envir = env, pattern = "^golden_done_", all.names = FALSE)
  nms <- setdiff(nms, "golden_done_ids")
  unique(unlist(lapply(nms, get, envir = env), use.names = FALSE))
}

golden_scenario_live <- function(id, phase) {
  phase <= golden_phase_done || id %in% golden_done_ids()
}

`%||%` <- function(x, y) if (is.null(x)) y else x

golden_dir <- function() test_path("golden")
golden_path <- function(...) file.path(golden_dir(), ...)

# Transitional Phase 2 routing, removed when WP-3G promotes the full baseline.
# Only inventoried Phase 2 scenarios use the authentic c215afd artifacts.
# Scenario input datasets and the legacy baseline remain untouched.
golden_phase2_ids <- c(sprintf("P%02d", 1:15), sprintf("K%02d", 1:9),
                       sprintf("S%02d", 1:8), "W15", sprintf("W%02d", 17:22))
golden_phase2_dir <- function() golden_path("phase2-2.5.1")
golden_baseline <- function(id) {
  golden_scenario(id)  # reject unknown IDs rather than silently falling back
  if (id %in% golden_phase2_ids) {
    list(dir = golden_phase2_dir(), tabtools = "2.5.1", fvgen = "1.2.7")
  } else {
    list(dir = golden_dir(), tabtools = "2.1.14", fvgen = "1.2.5")
  }
}
golden_artifact_path <- function(id, file) file.path(golden_baseline(id)$dir, file)

golden_scenarios <- function() {
  utils::read.csv(golden_path("scenarios.csv"), stringsAsFactors = FALSE,
                  encoding = "UTF-8", na.strings = character())
}

golden_scenario <- function(id) {
  sc <- golden_scenarios()
  row <- sc[sc$id == id, , drop = FALSE]
  if (nrow(row) != 1L) stop("Unknown golden scenario: ", id, call. = FALSE)
  as.list(row)
}

golden_mask <- function(mask) {
  if (length(mask) == 1L && !is.na(mask) && grepl(",", mask, fixed = TRUE)) {
    mask <- strsplit(mask, ",", fixed = TRUE)[[1]]
  }
  mask <- trimws(mask)
  mask[nzchar(mask) & !is.na(mask)]
}

# Header text of the columns each mask token hides. "pstyle" masks the
# p-dependent styling (boldp, highlight) rather than a column.
golden_mask_headers <- c(p = "p-value", test = "Test", statistic = "Statistic")

# ---------------------------------------------------------------------------
# Row-wise p mask (Phase 2 review P1-1/P1-2)
#
# The p token masks only the rows whose R test differs from Stata's (plan D3
# test map): contn/contln (Welch t or Welch ANOVA vs pooled t/ANOVA) and
# two-group conts (Wilcoxon: R's exact/continuity-corrected p vs ranksum).
# cat/bin (uncorrected Pearson chi-squared), cate/bine (Fisher's exact) and
# conts with more than two groups (Kruskal-Wallis, ties-adjusted) are the
# same tests, so their p cells, r(table) p_value, and p-dependent styling
# (boldp, highlight) are compared exactly. Test and Statistic stay masked on
# every row (the names differ). Without row metadata (a bare grid) the whole
# p column is masked as before.

# One flag per body row of a tt_table: TRUE where the p-value is masked.
golden_p_masked_rows <- function(tt) {
  vt <- tt$rows$vtype
  if (is.null(vt)) return(rep(TRUE, nrow(tt$body)))
  G <- sum(tt$cols$role == "group")
  !is.na(vt) & (vt %in% c("contn", "contln") | (vt == "conts" & G == 2L))
}

# The same flags on the rows of the csv() grid (tabtools:::.tt_grid): title,
# header, and footnote rows are never masked (header text is compared as is).
golden_grid_p_rows <- function(tt) {
  flags <- c(rep(FALSE, length(tt$header)), golden_p_masked_rows(tt))
  g <- tabtools:::.tt_cells(tt, extraspace = TRUE)
  while (nrow(g) && all(!nzchar(trimws(g[1, ])))) {
    g <- g[-1, , drop = FALSE]
    flags <- flags[-1]
  }
  c(if (nzchar(tt$title)) FALSE, flags, if (nzchar(tt$footnote)) FALSE)
}

# Kruskal-Wallis precision (Phase 3 review P2-4). Stata's kwallis keeps
# its ranks and rank sums in float variables (kwallis.ado:21 genrank with
# the default storage type; :25 by-group sum(); :40 `replace RankSum =
# sum(RankSum*RankSum/Obs)`, a float running sum of the squared rank sums),
# so its chi-squared carries ~1e-7 relative error that the statistic's
# cancellation (12/(N(N+1)) * sum - 3(N+1)) amplifies: probed in Stata 17,
# chi2_adj 15.4471157 vs kruskal.test() 15.4470955 (review probe I5,
# fweight, ties), 2.11950699 vs 2.11950750 (auto price by rep78, no ties),
# 22.2589297 vs 22.2589976 (3,000 distinct uniforms; p 5.76191e-5 vs
# 5.76172e-5). Ties are therefore not required for the drift. The displayed
# p cell of a >2-group conts row is still compared exactly; its r(table)
# p_value is compared at this relative tolerance. Every other p stays at
# the stored comparator's 1e-9.
golden_kwallis_p_tol <- 1e-4

# Flags per r(table) row (tt$rows$table_row maps body rows to it), with
# attribute "tol": the relative tolerance of each row's p_value (NA = the
# comparator's default), golden_kwallis_p_tol on >2-group conts rows.
golden_table_p_rows <- function(tt) {
  tr <- tt$rows$table_row
  if (is.null(tr) || is.null(tt$stored$table)) return(NULL)
  out <- rep(TRUE, nrow(tt$stored$table))
  tol <- rep(NA_real_, nrow(tt$stored$table))
  hit <- !is.na(tr)
  out[tr[hit]] <- golden_p_masked_rows(tt)[hit]
  G <- sum(tt$cols$role == "group")
  kw <- hit & !is.na(tt$rows$vtype) & tt$rows$vtype == "conts" & G > 2L
  tol[tr[kw]] <- golden_kwallis_p_tol
  structure(out, tol = tol)
}

# Derived small-cell suppression (Phase 3 review P1-1). "Suppressed" in a
# Test, Statistic or p-value cell does not depend on which test ran, and a
# leaked test name, statistic or p-value there is a disclosure regression
# (desctab.ado:790-833), so a masked cell is compared exactly whenever
# either side reads "Suppressed": every path (cells, CSV and Markdown
# sinks, console, xlsx values) treats it as outside the mask.
golden_suppressed <- function(x) trimws(x) == "Suppressed"

# R-side invariant behind the same finding: a Test/Statistic/p-value/SMD
# cell reads "Suppressed" exactly where the table's own suppression matrix
# codes it 3 (derived). The matrix rows are the two header rows, then the
# body rows. Returns mismatch descriptions.
golden_check_derived <- function(tt) {
  m <- tt$stored$suppression
  if (is.null(m)) return(character())
  role_of <- c(pvalue = "p", test = "test", statistic = "statistic", smd_str = "smd")
  body <- as.matrix(tt$body)
  why <- character()
  for (sc in intersect(colnames(m), names(role_of))) {
    j <- which(tt$cols$role == role_of[[sc]])
    if (length(j) != 1L) {
      why <- c(why, sprintf("suppression column %s has no table column", sc))
      next
    }
    code3 <- m[-(1:2), sc] == 3
    supp <- golden_suppressed(body[, j])
    bad <- which(code3 != supp)
    why <- c(why, sprintf("body row %d %s: '%s' with suppression code %s", bad, sc, body[bad, j],
                          m[bad + 2L, sc]))
  }
  why
}

# Stata's methods paragraph with R's test names swapped in (plan section 1):
# Stata's pooled t / ANOVA become R's Welch tests, and R drops the software
# sentence.
golden_methods_swap <- function(x) {
  x <- gsub("independent t-test", "Welch's t-test", x, fixed = TRUE)
  x <- gsub("one-way ANOVA", "Welch's one-way ANOVA", x, fixed = TRUE)
  sub(" Analysis performed in Stata [^ ]+ \\(StataCorp, College Station, TX\\)\\.$", "", x)
}

# regtab's methods sentence (Milestone H task H11, decision H-D3): R builds
# it from the models, and so does Stata tabtools 2.1.12 (take_action item
# 11, fixed; 2.1.11 picked it from the estimate header). A golden whose
# Stata sentence names the wrong model would be listed, with Stata's and
# R's sentences, in fixtures/regtab_methods/golden_divergences.csv (sets
# "golden", "regtab_5w_review", "regtab_phase5_review", "regtab_h_t2b"),
# and its r(methods) replaced by R's before the comparison: the documented
# transform, and the only relaxation of the methods comparison.
# test-golden-harness.R checks that each pair differs only in the estimate
# noun and the model phrase. The 70 rows of 2.1.11 were all dropped in C5;
# the clogit goldens R74-R76 (task 5.15) were listed until tabtools 2.1.14
# classified clogit (C8); the list is empty.
golden_methods_divergences <- local({
  cache <- NULL
  function() {
    if (is.null(cache)) {
      cache <<- utils::read.csv(test_path("fixtures", "regtab_methods", "golden_divergences.csv"),
                                stringsAsFactors = FALSE, encoding = "UTF-8")
    }
    cache
  }
})

golden_methods_regtab <- function(golden, id, set = "golden") {
  d <- golden_methods_divergences()
  k <- which(d$set == set & d$id == id)[1]
  if (is.na(k)) return(golden)
  m <- golden$name == "methods" & golden$kind == "macro"
  stata <- sub(" Analysis performed in Stata [^ ]+ \\(StataCorp, College Station, TX\\)\\.$", "", golden$value[m])
  if (!identical(stata, d$stata[k])) {
    stop(set, " ", id, " r(methods) is no longer the sentence listed in golden_divergences.csv: '",
         stata, "'", call. = FALSE)
  }
  golden$value[m] <- d$r[k]
  golden
}

# ---------------------------------------------------------------------------
# Fixtures

#' Read a golden fixture exactly as the Stata side saw it.
#'
#' Columns named in `factors` become factors through the public
#' tabtools::tt_as_factor() (review P1-1: the tests take the path users
#' take): levels follow the value labels in ascending code order (or the
#' sorted codes when unlabelled), the Stata codes stay in the "labels"
#' attribute, and the variable label in "label".
# Fixtures kept out of the package build (.Rbuildignore): the tests that
# read them skip when the fixture is absent, i.e. under R CMD check of the
# tarball. A source checkout (devtools::test()) has them all, and there a
# missing one is an error, not a skip.
# - cohort_pp (4.5 MB; pre-release review P2-1);
# - the StataCorp example datasets and extracts of them (sysuse auto;
#   webuse nhanes2, union, cattaneo2, bdsianesi5; autolong is auto with
#   longer labels), which are not ours to redistribute (user decision
#   2026-09-27: keep them out of the tarball).
golden_source_only_fixtures <- c("cohort_pp", "auto", "autolong", "nhanes2", "union",
                                 "cattaneo2", "bdsianesi5")

# Scenarios whose goldens are kept out of the package build for the same
# reason: they list rows of auto verbatim (P02: the first ten cars; P09:
# three makes), so their csv, md, stored, console and workbook (<id>.xlsx,
# not a sheet of the shipped puttab.xlsx) are .Rbuildignored. Their tests
# skip through golden_fixture("auto"); inventory checks leave them out
# with golden_ids_in_build().
golden_source_only_ids <- c("P02", "P09")
golden_ids_in_build <- function(ids) {
  if (golden_in_source()) ids else setdiff(ids, golden_source_only_ids)
}

# A source checkout: qa/ is .Rbuildignored, so it is absent from the
# tarball, an unpacked tarball, R CMD check, and an --install-tests
# install, where the source-only files are missing too (R/ is not: it is
# in the tarball).
golden_in_source <- function() dir.exists(test_path("..", "..", "qa"))

# The Stata workbook holding scenario `id`'s sheet: stacktab scenarios and
# any scenario whose Stata call names `using "@ID@.xlsx"` (P02, P09) have
# their own <id>.xlsx; every other scenario's sheet is in <command>.xlsx.
golden_book_name <- function(id) {
  sc <- golden_scenario(id)
  own <- sc$command == "stacktab" || grepl("using \"@ID@.xlsx\"", sc$stata_call, fixed = TRUE)
  paste0(if (own) id else sc$command, ".xlsx")
}
golden_book <- function(id) golden_artifact_path(id, golden_book_name(id))

# The path of a golden fixture, or a skip when it is a source-only fixture
# and this is not a source checkout. Every reader of a fixture file goes
# through here (golden_fixture(), or a direct haven::read_dta()).
golden_fixture_path <- function(name) {
  path <- golden_path("fixtures", paste0(name, ".dta"))
  if (name %in% golden_source_only_fixtures && !file.exists(path) && !golden_in_source()) {
    testthat::skip(paste0(name, ".dta is not in the package build (source checkout only)"))
  }
  path
}

golden_fixture <- function(name, factors = NULL) {
  testthat::skip_if_not_installed("haven")
  path <- golden_fixture_path(name)
  d <- haven::read_dta(path)
  d <- as.data.frame(d)
  if (length(factors)) d <- tabtools::tt_as_factor(d, vars = factors)
  d
}

# ---------------------------------------------------------------------------
# Reading goldens

# Visible cells of a golden CSV sink: character matrix, no trimming, empty
# fields kept as "".
golden_read_cells_file <- function(path) {
  # blank.lines.skip = FALSE: a one-column table's blank cell is an empty
  # line (puttab golden P10).
  x <- utils::read.csv(path, header = FALSE, colClasses = "character",
                       strip.white = FALSE, na.strings = character(),
                       encoding = "UTF-8", check.names = FALSE, blank.lines.skip = FALSE)
  m <- as.matrix(x)
  dimnames(m) <- NULL
  m
}

golden_read_cells <- function(id) golden_read_cells_file(golden_artifact_path(id, paste0(id, ".csv")))

golden_read_stored <- function(id) {
  utils::read.csv(golden_artifact_path(id, paste0(id, "_stored.csv")), colClasses = "character",
                  na.strings = character(), encoding = "UTF-8")
}

golden_read_lines <- function(path) readLines(path, warn = FALSE, encoding = "UTF-8")

# Per-case provenance is checked independently of numeric stored results.
# Golden comparisons intentionally ignore metadata; routing must not.
golden_compare_provenance <- function(stored, id) {
  b <- golden_baseline(id)
  keys <- c("_golden_id", "_golden_tabtools_version", "_golden_fvgen_version")
  meta <- stored[stored$kind == "meta" & stored$name %in% keys, , drop = FALSE]
  want <- c(id, b$tabtools, b$fvgen)
  why <- character()
  for (i in seq_along(keys)) {
    got <- meta$value[meta$name == keys[i]]
    if (!identical(got, want[i])) why <- c(why, paste(keys[i], "provenance mismatch"))
  }
  why
}

# ---------------------------------------------------------------------------
# Cells

# The CSV-shaped cell grid of a tt_table: [title] + header rows + body +
# [footnote], matching the Stata csv() sink (task 1.8). Anything that is
# already a matrix or data frame is taken as that grid.
golden_as_cells <- function(x) {
  if (inherits(x, "tt_table") && !is.null(x$cols) &&
      exists(".tt_grid", envir = asNamespace("tabtools"), inherits = FALSE)) {
    # The csv() sink's grid, including the sink-only extraspace prefix.
    x <- tabtools:::.tt_grid(x)
  } else if (inherits(x, "tt_table")) {
    body <- as.matrix(x$body)
    nc <- ncol(body)
    pad <- function(v) c(v, rep("", nc - length(v)))
    rows <- list()
    if (length(x$title) && nzchar(x$title)) rows <- c(rows, list(pad(x$title)))
    for (h in x$header) rows <- c(rows, list(pad(h$text)))
    rows <- c(rows, lapply(seq_len(nrow(body)), function(i) body[i, ]))
    if (length(x$footnote) && nzchar(x$footnote)) rows <- c(rows, list(pad(x$footnote)))
    x <- do.call(rbind, rows)
  }
  m <- as.matrix(x)
  storage.mode(m) <- "character"
  m[is.na(m)] <- ""
  dimnames(m) <- NULL
  m
}

# Columns hidden by the mask, found by header text in the rows above the
# first body row (any row whose cell equals the masked header).
golden_masked_cols <- function(want, mask, header_rows = 4L) {
  heads <- golden_mask_headers[intersect(golden_mask(mask), names(golden_mask_headers))]
  if (!length(heads)) return(integer())
  top <- want[seq_len(min(header_rows, nrow(want))), , drop = FALSE]
  # Trimmed: extraspace prefixes the p-value header (" p-value", golden T33).
  which(apply(top, 2L, function(col) any(trimws(col) %in% heads)))
}

# Numbers inside a cell, commas removed ("5,351 (60)" -> 5351, 60), each with
# the unit of its last displayed digit.
golden_cell_numbers <- function(s) {
  pat <- "[-+]?[0-9][0-9,]*(\\.[0-9]+)?(e[-+][0-9]+)?"
  tok <- regmatches(s, gregexpr(pat, s, perl = TRUE))[[1]]
  if (!length(tok)) return(data.frame(value = numeric(), unit = numeric()))
  clean <- gsub(",", "", tok, fixed = TRUE)
  mant <- sub("e.*$", "", clean)
  dec <- ifelse(grepl(".", mant, fixed = TRUE), nchar(sub("^[^.]*\\.", "", mant)), 0L)
  expo <- ifelse(grepl("e", clean, fixed = TRUE), as.numeric(sub("^.*e", "", clean)), 0)
  data.frame(value = as.numeric(clean), unit = 10^(expo - dec))
}

golden_cell_skeleton <- function(s) {
  gsub("[-+]?[0-9][0-9,]*(\\.[0-9]+)?(e[-+][0-9]+)?", "#", s, perl = TRUE)
}

#' Compare two cell grids.
#'
#' mode "exact": every unmasked cell identical. "tolerance": the label column
#' and every cell's non-numeric skeleton identical, numbers within one unit of
#' the golden's last displayed digit. "structure": skeletons identical, numbers
#' ignored. Masked columns keep their header text and blank/non-blank pattern.
golden_compare_cells <- function(got, want, mask = character(), mode = "exact", p_rows = NULL) {
  mode <- match.arg(mode, c("exact", "tolerance", "structure"))
  if (is.null(p_rows) && inherits(got, "tt_table") && !is.null(got$rows$vtype)) p_rows <- golden_grid_p_rows(got)
  got <- golden_as_cells(got)
  want <- golden_as_cells(want)
  if (!identical(dim(got), dim(want))) {
    return(data.frame(row = NA_integer_, col = NA_integer_,
                      got = paste(dim(got), collapse = "x"),
                      want = paste(dim(want), collapse = "x"), why = "dimensions"))
  }
  masked <- golden_masked_cols(want, mask)
  p_col <- intersect(masked, golden_masked_cols(want, "p"))
  if (!is.null(p_rows) && length(p_rows) != nrow(want)) p_rows <- NULL
  heads <- golden_mask_headers
  out <- list()
  for (j in seq_len(ncol(want))) {
    for (i in seq_len(nrow(want))) {
      g <- got[i, j]
      w <- want[i, j]
      row_masked <- !(j %in% p_col) || is.null(p_rows) || p_rows[i]
      if (j %in% masked && row_masked && !(trimws(w) %in% heads) &&
          !golden_suppressed(g) && !golden_suppressed(w)) {
        if (nzchar(trimws(g)) != nzchar(trimws(w))) {
          out[[length(out) + 1L]] <- data.frame(row = i, col = j, got = g, want = w, why = "masked blank pattern")
        }
        next
      }
      if (identical(g, w)) next
      why <- NULL
      if (mode == "exact" || j == 1L) {
        why <- "text"
      } else if (!identical(golden_cell_skeleton(g), golden_cell_skeleton(w))) {
        why <- "skeleton"
      } else if (mode == "tolerance") {
        gn <- golden_cell_numbers(g)
        wn <- golden_cell_numbers(w)
        if (any(abs(gn$value - wn$value) > wn$unit * (1 + 1e-9))) why <- "tolerance"
      }
      if (!is.null(why)) out[[length(out) + 1L]] <- data.frame(row = i, col = j, got = g, want = w, why = why)
    }
  }
  if (!length(out)) return(data.frame(row = integer(), col = integer(), got = character(), want = character(), why = character()))
  do.call(rbind, out)
}

golden_fail <- function(mm, what, n = 8L) {
  if (!nrow(mm)) return(invisible(TRUE))
  show <- utils::head(mm, n)
  lines <- apply(show, 1L, function(r) paste(paste0(names(r), "=", encodeString(r, quote = "'")), collapse = " "))
  testthat::fail(paste0(what, ": ", nrow(mm), " mismatch(es)\n", paste(lines, collapse = "\n")))
}

expect_cells_match <- function(tt, id, mask = NULL, mode = NULL) {
  sc <- golden_scenario(id)
  mask <- if (is.null(mask)) sc$mask else mask
  mode <- if (is.null(mode)) sc$compare else mode
  parts <- golden_publication_cells(tt, id)
  mm <- golden_compare_cells(parts$got, parts$want, mask, mode,
                              p_rows = if (!is.null(tt$rows$vtype)) golden_grid_p_rows(tt))
  if (nrow(mm)) golden_fail(mm, paste("cells", id)) else testthat::succeed()
  invisible(mm)
}

# ---------------------------------------------------------------------------
# CSV / Markdown sinks

golden_bytes <- function(path) readBin(path, "raw", file.info(path)$size)

golden_mask_md_line <- function(line, cols) {
  # Split on pipes not escaped with a backslash; cells keep their padding.
  parts <- strsplit(line, "(?<!\\\\)\\|", perl = TRUE)[[1]]
  cells <- parts[-1L]
  for (j in cols) {
    if (j <= length(cells) && !golden_suppressed(cells[j])) {
      cells[j] <- if (nzchar(trimws(cells[j]))) " # " else cells[j]
    }
  }
  paste0(parts[1L], "|", paste(cells, collapse = "|"), "|")
}

# `p_body`: row-wise p flags per table body row (restarting for every table
# in an mdappend file); NULL masks the whole p column.
golden_mask_md <- function(lines, mask, p_body = NULL) {
  heads <- golden_mask_headers[intersect(golden_mask(mask), names(golden_mask_headers))]
  if (!length(heads)) return(lines)
  cols <- integer()
  pcol <- integer()
  k <- 0L
  for (i in seq_along(lines)) {
    ln <- lines[i]
    if (!startsWith(ln, "|")) {
      cols <- integer()
      next
    }
    nxt <- if (i < length(lines)) lines[i + 1L] else ""
    if (grepl("^\\|( --- \\|)+$", nxt)) {
      cells <- trimws(strsplit(ln, "(?<!\\\\)\\|", perl = TRUE)[[1]][-1L])
      cols <- which(cells %in% heads)
      pcol <- which(cells == "p-value")
      k <- 0L
      next
    }
    if (length(cols) && !grepl("^\\|( --- \\|)+$", ln)) {
      k <- k + 1L
      use <- cols
      if (!is.null(p_body) && k <= length(p_body) && !p_body[k]) use <- setdiff(cols, pcol)
      lines[i] <- golden_mask_md_line(ln, use)
    }
  }
  lines
}

#' Compare a CSV or Markdown sink with its golden. Unmasked: byte identical.
#' Masked: identical after masked cells are replaced (blank pattern kept), and
#' identical line endings and trailing newline.
golden_compare_sink <- function(path, golden, mask = character(), p_rows = NULL, p_body = NULL) {
  mask <- golden_mask(mask)
  gb <- golden_bytes(path)
  wb <- golden_bytes(golden)
  if (!length(intersect(mask, names(golden_mask_headers)))) {
    if (identical(gb, wb)) return(character())
    return(sprintf("bytes differ (%d vs %d bytes)", length(gb), length(wb)))
  }
  why <- character()
  crlf <- function(b) sum(b[-1L] == as.raw(10L) & b[-length(b)] == as.raw(13L))
  if (crlf(gb) != crlf(wb)) why <- c(why, "line endings differ")
  last <- function(b) if (length(b)) b[length(b)] else as.raw(0L)
  if (!identical(last(gb), last(wb))) why <- c(why, "trailing newline differs")
  if (grepl("\\.csv$", golden)) {
    g <- golden_read_cells_file(path)
    w <- golden_read_cells_file(golden)
    if (!is.null(p_rows) && length(p_rows) != nrow(w)) p_rows <- NULL
    mm <- golden_compare_cells(g, w, mask, "exact", p_rows = p_rows)
    if (nrow(mm)) why <- c(why, sprintf("row %s col %s: '%s' vs '%s'", mm$row, mm$col, mm$got, mm$want))
    # Quoting must match too: compare raw lines with masked fields removed.
    mc <- golden_masked_cols(w, mask)
    pc <- intersect(mc, golden_masked_cols(w, "p"))
    strip <- function(p) {
      ln <- golden_read_lines(p)
      vapply(seq_along(ln), function(i) {
        l <- ln[i]
        f <- scan(text = l, what = "", sep = ",", quote = "\"", quiet = TRUE,
                  na.strings = character(), strip.white = FALSE, allowEscapes = FALSE)
        raw <- strsplit(l, ",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)", perl = TRUE)[[1]]
        if (length(raw) < length(f)) raw <- c(raw, rep("", length(f) - length(raw)))
        hide <- mc
        if (!is.null(p_rows) && i <= length(p_rows) && !p_rows[i]) hide <- setdiff(mc, pc)
        hide <- hide[hide <= length(raw)]
        raw[hide[!golden_suppressed(gsub('"', "", raw[hide], fixed = TRUE))]] <- "#"
        paste(raw, collapse = ",")
      }, "", USE.NAMES = FALSE)
    }
    gs <- strip(path)
    ws <- strip(golden)
    if (!identical(gs, ws)) why <- c(why, "CSV quoting or field layout differs")
  } else {
    g <- golden_mask_md(golden_read_lines(path), mask, p_body)
    w <- golden_mask_md(golden_read_lines(golden), mask, p_body)
    if (length(g) != length(w)) {
      why <- c(why, sprintf("%d vs %d lines", length(g), length(w)))
    } else if (!identical(g, w)) {
      k <- which(g != w)
      why <- c(why, sprintf("line %d: '%s' vs '%s'", k, g[k], w[k]))
    }
  }
  unique(why)
}

expect_sink_match <- function(path, id, ext = tools::file_ext(path), mask = NULL, tt = NULL) {
  sc <- golden_scenario(id)
  mask <- if (is.null(mask)) sc$mask else mask
  p_rows <- if (!is.null(tt$rows$vtype)) golden_grid_p_rows(tt)
  p_body <- if (!is.null(tt$rows$vtype)) golden_p_masked_rows(tt)
  why <- if (is.null(tt)) {
    golden_compare_sink(path, golden_artifact_path(id, paste0(id, ".", ext)), mask, p_rows = p_rows, p_body = p_body)
  } else golden_publication_sink(path, id, ext, mask, tt)
  if (length(why)) {
    testthat::fail(paste0(ext, " sink ", id, ":\n", paste(utils::head(why, 8L), collapse = "\n")))
  } else {
    testthat::succeed()
  }
  invisible(why)
}

# ---------------------------------------------------------------------------
# Console listing

# The boxed Stata listing only: rejoin lines Stata's log wrapped at the
# linesize ("> " continuations), drop the chatter commands inside the engine
# print before the box ("(1 real change made)"), and drop the sink messages
# printed after it ("CSV exported to", "Markdown exported to", "Exported 7
# rows ...").
golden_console_box <- function(lines) {
  out <- character()
  for (l in lines) {
    if (startsWith(l, "> ") && length(out)) {
      out[length(out)] <- paste0(out[length(out)], substring(l, 3L))
    } else {
      out <- c(out, l)
    }
  }
  box <- which(grepl("^\\s*\\+-+\\+\\s*$", out))
  if (length(box) && box[1] > 1L) {
    pre <- seq_len(box[1] - 1L)
    chatter <- pre[grepl("^\\s*\\(.*\\)\\s*$", out[pre]) | !nzchar(trimws(out[pre]))]
    if (length(chatter)) out <- out[-chatter]
  }
  out <- out[!grepl("^(CSV exported to|Markdown exported to|Exported [0-9]+ rows)", out)]
  while (length(out) && !nzchar(trimws(out[length(out)]))) out <- out[-length(out)]
  out
}

golden_is_box_line <- function(l) grepl("^\\s*[|+]", l)
golden_is_rule_line <- function(l) grepl("^\\s*[|+]-+[|+]\\s*$", l)

# Character span of the masked columns, read off the first box row that
# carries a masked header: from the first masked header's start to just
# before the next unmasked header (or the closing border), plus the start of
# each masked column (its header's start; the columns are left-justified).
# Masked columns are assumed contiguous, as they are in table1_tc (Test,
# Statistic, p-value).
golden_console_span <- function(lines, heads) {
  for (l in lines[golden_is_box_line(lines) & !golden_is_rule_line(lines)]) {
    m <- gregexpr("[^ |]+( [^ |]+)*", l)[[1]]
    if (m[1] < 0) next
    tok <- regmatches(l, list(m))[[1]]
    hit <- which(tok %in% heads)
    if (!length(hit)) next
    start <- m[min(hit)]
    after <- setdiff(seq_along(tok), seq_len(max(hit)))
    bar <- max(gregexpr("|", l, fixed = TRUE)[[1]])
    end <- if (length(after)) m[min(after)] - 1L else bar - 1L
    return(structure(c(start, end), cols = as.integer(m[hit])))
  }
  NULL
}

# Split each line around the masked span; within it each masked column
# reduces to "#" (non-blank), "" (blank) or "Suppressed" (compared exactly,
# golden_suppressed()), so masked text and width may otherwise differ
# between sides.
golden_console_masked <- function(lines, heads) {
  span <- golden_console_span(lines, heads)
  cols <- attr(span, "cols")
  lapply(lines, function(l) {
    if (is.null(span) || !golden_is_box_line(l)) return(l)
    mark <- ""
    if (!golden_is_rule_line(l)) {
      ends <- c(cols[-1L] - 1L, span[2])
      cells <- trimws(substring(l, cols, ends))
      mark <- paste(ifelse(golden_suppressed(cells), "Suppressed", ifelse(nzchar(cells), "#", "")),
                    collapse = "\t")
    }
    c(substr(l, 1L, span[1] - 1L), mark, substring(l, span[2] + 1L))
  })
}

golden_compare_console <- function(lines, golden_lines, mask = character()) {
  # "r_notes": R-only informational notes (cli's "i" lines with their
  # indented continuation lines and the once-per-session line) are dropped
  # from the R side; Stata prints nothing in their place (user decision
  # 2026-09-28: the multinom base-outcome note, demo C15).
  if ("r_notes" %in% golden_mask(mask)) lines <- golden_strip_r_notes(lines)
  g <- golden_console_box(lines)
  w <- golden_console_box(golden_lines)
  heads <- golden_mask_headers[intersect(golden_mask(mask), names(golden_mask_headers))]
  if (length(g) != length(w)) return(sprintf("%d vs %d lines", length(g), length(w)))
  if (!length(heads)) {
    k <- which(g != w)
    return(sprintf("line %d: '%s' vs '%s'", k, g[k], w[k]))
  }
  gc <- golden_console_masked(g, heads)
  wc <- golden_console_masked(w, heads)
  bad <- which(!mapply(identical, gc, wc))
  vapply(bad, function(k) sprintf("line %d: [%s] vs [%s]", k,
                                  paste(gc[[k]], collapse = "|#|"), paste(wc[[k]], collapse = "|#|")), "")
}

golden_strip_r_notes <- function(lines) {
  drop <- logical(length(lines))
  inside <- FALSE
  for (k in seq_along(lines)) {
    l <- lines[k]
    if (startsWith(l, "\u2139 ") || startsWith(l, "i ")) {
      inside <- TRUE
    } else if (inside && !(startsWith(l, "  ") || grepl("^This message is displayed once", l))) {
      inside <- FALSE
    }
    drop[k] <- inside
  }
  lines[!drop]
}

expect_console_match <- function(tt, id, mask = NULL) {
  sc <- golden_scenario(id)
  mask <- if (is.null(mask)) sc$mask else mask
  lines <- if (is.character(tt)) tt else utils::capture.output(print(tt))
  parts <- golden_publication_console(lines, golden_read_lines(golden_artifact_path(id, paste0(id, "_console.txt"))), id)
  why <- golden_compare_console(parts$got, parts$want, mask)
  if (length(why)) {
    testthat::fail(paste0("console ", id, ":\n", paste(utils::head(why, 8L), collapse = "\n")))
  } else {
    testthat::succeed()
  }
  invisible(why)
}

# ---------------------------------------------------------------------------
# Stored results (the r() analogue)

# Flatten a stored-results list to the golden's name/kind/row/col/value shape.
# Length-1 numerics are scalars, character strings macros, matrices matrices.
golden_flatten_stored <- function(stored) {
  rows <- list()
  for (nm in names(stored)) {
    v <- stored[[nm]]
    if (is.matrix(v)) {
      rn <- rownames(v) %||% as.character(seq_len(nrow(v)))
      cn <- colnames(v) %||% as.character(seq_len(ncol(v)))
      idx <- expand.grid(i = seq_len(nrow(v)), j = seq_len(ncol(v)))
      rows[[nm]] <- data.frame(name = nm, kind = "matrix", row = rn[idx$i], col = cn[idx$j],
                               value = format_stored_num(v[cbind(idx$i, idx$j)]))
    } else if (is.character(v)) {
      rows[[nm]] <- data.frame(name = nm, kind = "macro", row = "", col = "", value = v[1L])
    } else if (is.numeric(v) && length(v) == 1L) {
      rows[[nm]] <- data.frame(name = nm, kind = "scalar", row = "", col = "", value = format_stored_num(v))
    }
  }
  if (!length(rows)) return(data.frame(name = character(), kind = character(), row = character(),
                                       col = character(), value = character()))
  out <- do.call(rbind, rows)
  rownames(out) <- NULL
  out
}

format_stored_num <- function(x) ifelse(is.na(x), ".", sprintf("%.17g", x))

# Stata missing values (".", ".a" ... ".z") compare equal to R's NA.
golden_stored_num <- function(s) {
  out <- exact_num(s)
  out[grepl("^\\.[a-z]?$", s)] <- NA_real_
  out
}

#' Compare stored results. `fields` restricts the names compared (default:
#' every non-meta golden field); numeric values within `tolerance` (relative
#' above 1, absolute below). Mask token "p": the table matrix's p_value is
#' dropped on the rows flagged in `p_table` (one flag per r(table) row; NULL
#' = every row), and `methods` is compared after golden_methods_swap(). An
#' unmasked r(table) p_value whose row has a non-NA `attr(p_table, "tol")`
#' is compared at that relative tolerance instead (golden_kwallis_p_tol).
#' Repeated keys (r(table) row names such as "___Missing") are matched by
#' occurrence.
golden_compare_stored <- function(stored, golden, fields = NULL, mask = character(), tolerance = 1e-9,
                                  p_table = NULL) {
  # P.4 retains richer R mask metadata. Pinned native r(smallcells) is the
  # scalar threshold, so project only that explicitly named native field.
  # The caller's canonical list and its other metadata remain untouched.
  if (!is.data.frame(stored) && is.list(stored$smallcells) &&
      any(golden$name == "smallcells" & golden$kind == "scalar")) {
    stored$smallcells <- stored$smallcells$threshold
  }
  got <- if (is.data.frame(stored)) stored else golden_flatten_stored(stored)
  key <- function(d) {
    k <- paste(d$name, d$kind, d$row, d$col, sep = "\r")
    paste(k, stats::ave(seq_along(k), k, FUN = seq_along), sep = "\r")
  }
  want <- golden[golden$kind != "meta", , drop = FALSE]
  want$key <- key(want)
  if (!is.null(fields)) want <- want[want$name %in% fields, , drop = FALSE]
  want_all <- want
  is_tab <- want$name == "table"
  idx <- rep(NA_integer_, nrow(want))
  if (any(is_tab)) idx[is_tab] <- cumsum(want$col[is_tab] == want$col[is_tab][1])
  row_tol <- rep(NA_real_, nrow(want))
  ptol <- attr(p_table, "tol")
  if (!is.null(ptol)) {
    k <- which(is_tab & want$col == "p_value" & !is.na(idx) & idx <= length(ptol))
    row_tol[k] <- ptol[idx[k]]
  }
  if ("p" %in% golden_mask(mask)) {
    masked <- if (is.null(p_table)) rep(TRUE, nrow(want)) else
      is.na(idx) | idx > length(p_table) | p_table[pmin(pmax(idx, 1L), length(p_table))]
    drop <- is_tab & want$col == "p_value" & masked
    want <- want[!drop, , drop = FALSE]
    row_tol <- row_tol[!drop]
    m <- want$name == "methods"
    want$value[m] <- golden_methods_swap(want$value[m])
  }
  # The Stata-only software sentence closing r(methods) ("Analysis performed
  # in Stata 17 (StataCorp, College Station, TX).") has no R counterpart. The
  # p-masked path drops it in golden_methods_swap(); unmasked goldens
  # (regtab) drop it here, and nothing else in methods is relaxed.
  meth <- want$name == "methods" & want$kind == "macro"
  want$value[meth] <- sub(" Analysis performed in Stata [^ ]+ \\(StataCorp, College Station, TX\\)\\.$", "",
                          want$value[meth])
  gk <- key(got)
  why <- character()
  # Two-way (Phase 4 review P1-4): a result R produces under a name the
  # golden has, but the golden lacks (an extra r(table) row, a repeated
  # macro), is a mismatch too. Names the golden does not have at all
  # (R-only results such as N_models) are not compared. Keys the p mask
  # removed from `want` still count as present.
  have <- want_all$key[want_all$name %in% want$name]
  extra <- got$name %in% want$name & got$kind != "meta" & !gk %in% have
  for (i in which(extra)) {
    why <- c(why, sprintf("extra %s %s[%s,%s] = '%s'", got$kind[i], got$name[i], got$row[i], got$col[i], got$value[i]))
  }
  for (i in seq_len(nrow(want))) {
    hit <- match(want$key[i], gk)
    if (is.na(hit)) {
      why <- c(why, sprintf("missing %s %s[%s,%s]", want$kind[i], want$name[i], want$row[i], want$col[i]))
      next
    }
    g <- got$value[hit]
    w <- want$value[i]
    if (want$kind[i] %in% c("scalar", "matrix")) {
      gn <- golden_stored_num(g)
      wn <- golden_stored_num(w)
      lim <- if (is.na(row_tol[i])) tolerance * max(1, abs(wn)) else row_tol[i] * abs(wn)
      same <- (is.na(gn) && is.na(wn)) || (!is.na(gn) && !is.na(wn) && abs(gn - wn) <= lim)
    } else {
      same <- identical(g, w)
    }
    if (!same) why <- c(why, sprintf("%s[%s,%s]: '%s' vs '%s'", want$name[i], want$row[i], want$col[i], g, w))
  }
  why
}

expect_stored_match <- function(tt, id, fields = NULL, mask = NULL, tolerance = 1e-9) {
  sc <- golden_scenario(id)
  mask <- if (is.null(mask)) sc$mask else mask
  stored <- if (inherits(tt, "tt_table")) tt$stored else tt
  p_table <- if (inherits(tt, "tt_table")) golden_table_p_rows(tt)
  golden <- golden_read_stored(id)
  if (identical(sc$command, "regtab")) golden <- golden_methods_regtab(golden, id)
  why <- golden_compare_stored(stored, golden, fields, mask, tolerance, p_table = p_table)
  if (length(why)) {
    testthat::fail(paste0("stored ", id, ":\n", paste(utils::head(why, 8L), collapse = "\n")))
  } else {
    testthat::succeed()
  }
  invisible(why)
}

# ---------------------------------------------------------------------------
# Excel styling

# Stata's xl() column widths read back this much wider than the value set;
# openxlsx2 (tt_write_xlsx) adds 0.711.
golden_width_offset <- 0.7109375
golden_r_width_offset <- 0.711

# Worksheet XML for a sheet name (via workbook.xml + its rels), unzipped.
golden_sheet_xml <- function(xlsx, sheet) {
  tmp <- tempfile("xlsx")
  dir.create(tmp)
  on.exit(unlink(tmp, recursive = TRUE))
  utils::unzip(xlsx, files = c("xl/workbook.xml", "xl/_rels/workbook.xml.rels"), exdir = tmp)
  wb <- paste(readLines(file.path(tmp, "xl/workbook.xml"), warn = FALSE, encoding = "UTF-8"), collapse = "")
  rel <- paste(readLines(file.path(tmp, "xl/_rels/workbook.xml.rels"), warn = FALSE), collapse = "")
  sheets <- regmatches(wb, gregexpr("<sheet [^>]*>", wb))[[1]]
  attr_of <- function(tag, a) sub(paste0('^.*\\b', a, '="([^"]*)".*$'), "\\1", tag)
  names <- vapply(sheets, attr_of, "", a = "name", USE.NAMES = FALSE)
  names <- gsub("&amp;", "&", names, fixed = TRUE)
  rid <- vapply(sheets, attr_of, "", a = "r:id", USE.NAMES = FALSE)[match(sheet, names)]
  if (is.na(rid)) stop("Sheet not found: ", sheet, call. = FALSE)
  rels <- regmatches(rel, gregexpr("<Relationship [^>]*>", rel))[[1]]
  target <- vapply(rels, attr_of, "", a = "Target", USE.NAMES = FALSE)[
    vapply(rels, attr_of, "", a = "Id", USE.NAMES = FALSE) == rid]
  target <- sub("^/?(xl/)?", "xl/", target)
  utils::unzip(xlsx, files = target, exdir = tmp)
  paste(readLines(file.path(tmp, target), warn = FALSE, encoding = "UTF-8"), collapse = "")
}

golden_sheet_layout <- function(xlsx, sheet) {
  xml <- golden_sheet_xml(xlsx, sheet)
  merges <- sub('^.*ref="([^"]*)".*$', "\\1", regmatches(xml, gregexpr("<mergeCell [^>]*>", xml))[[1]])
  rowtags <- regmatches(xml, gregexpr("<row [^>]*>", xml))[[1]]
  ht <- grepl('\\bcustomHeight="(1|true)"', rowtags) | grepl('\\bht="', rowtags)
  heights <- data.frame(
    row = as.integer(sub('^.*\\br="([0-9]+)".*$', "\\1", rowtags[ht])),
    height = as.numeric(sub('^.*\\bht="([^"]*)".*$', "\\1", rowtags[ht]))
  )
  coltags <- regmatches(xml, gregexpr("<col [^>]*>", xml))[[1]]
  widths <- do.call(rbind, lapply(coltags, function(t) {
    lo <- as.integer(sub('^.*\\bmin="([0-9]+)".*$', "\\1", t))
    hi <- as.integer(sub('^.*\\bmax="([0-9]+)".*$', "\\1", t))
    w <- if (grepl('\\bwidth="', t)) as.numeric(sub('^.*\\bwidth="([^"]*)".*$', "\\1", t)) else NA_real_
    data.frame(col = seq.int(lo, min(hi, lo + 50L)), width = w)
  }))
  list(merges = sort(merges), heights = heights[order(heights$row), , drop = FALSE],
       widths = if (is.null(widths)) data.frame(col = integer(), width = numeric()) else widths)
}

golden_merge_nonanchors <- function(merges) {
  out <- character()
  for (m in merges) {
    ends <- strsplit(m, ":", fixed = TRUE)[[1]]
    if (length(ends) != 2L) next
    rc <- function(a) c(as.integer(sub("^[A-Z]+", "", a)), golden_col_index(sub("[0-9]+$", "", a)))
    a <- rc(ends[1]); b <- rc(ends[2])
    cells <- expand.grid(r = a[1]:b[1], c = a[2]:b[2])
    cells <- cells[!(cells$r == a[1] & cells$c == a[2]), ]
    out <- c(out, paste0(golden_col_letters(cells$c), cells$r))
  }
  out
}

golden_col_index <- function(letters) {
  vapply(strsplit(letters, ""), function(ch) {
    Reduce(function(acc, x) acc * 26L + x, match(ch, LETTERS), 0L)
  }, 0L)
}

golden_col_letters <- function(n) {
  vapply(n, function(k) {
    s <- ""
    while (k > 0) {
      r <- (k - 1L) %% 26L
      s <- paste0(LETTERS[r + 1L], s)
      k <- (k - 1L) %/% 26L
    }
    s
  }, "")
}

# One row per cell with the formatting attributes the parity contract covers.
golden_cell_styles <- function(xlsx, sheet) {
  testthat::skip_if_not_installed("tidyxl")
  cells <- tidyxl::xlsx_cells(xlsx, sheets = sheet)
  fmt <- tidyxl::xlsx_formats(xlsx)$local
  i <- cells$local_format_id
  txt <- ifelse(is.na(cells$character), "", cells$character)
  num <- !is.na(cells$numeric)
  txt[num] <- format_stored_num(cells$numeric[num])
  border <- function(side) {
    st <- fmt$border[[side]]$style[i]
    ifelse(is.na(st) | st == "none", NA_character_, st)
  }
  data.frame(
    address = cells$address, row = cells$row, col = cells$col, value = txt,
    bold = fmt$font$bold[i], italic = fmt$font$italic[i],
    font = fmt$font$name[i], size = fmt$font$size[i], number_format = fmt$numFmt[i], format_id = i,
    font_color = fmt$font$color$rgb[i] %|NA|% "",
    halign = fmt$alignment$horizontal[i], valign = fmt$alignment$vertical[i],
    wrap = fmt$alignment$wrapText[i],
    border_top = border("top"), border_bottom = border("bottom"),
    border_left = border("left"), border_right = border("right"),
    fill = ifelse(is.na(fmt$fill$patternFill$patternType[i]) | fmt$fill$patternFill$patternType[i] == "none",
                  "", fmt$fill$patternFill$fgColor$rgb[i] %|NA|% ""),
    stringsAsFactors = FALSE
  )
}

`%|NA|%` <- function(x, y) ifelse(is.na(x), y, x)

golden_style_attrs <- c("value", "bold", "italic", "font", "size", "font_color", "halign",
                        "valign", "wrap", "border_top", "border_bottom", "border_left",
                        "border_right", "fill")

#' Compare the formatting of two worksheets cell by cell, plus merged ranges,
#' explicit row heights, and column widths (within `width_tol` after removing
#' each side's read-back offset). Non-anchor cells of merged ranges are
#' skipped. Mask tokens: p/test/statistic hide those columns' body values
#' (blank pattern kept); "pstyle" ignores bold on p cells and the highlight
#' row fill, which depend on the test p-value. `p_rows` (one flag per body
#' row, golden_p_masked_rows()) limits the p-value and pstyle masks to the
#' flagged rows; worksheet row 4 is the first body row (row 1 is the title
#' row, reserved even when empty, rows 2-3 the header).
golden_compare_styles <- function(got_xlsx, got_sheet, want_xlsx, want_sheet, mask = character(),
                                  got_width_offset = 0, want_width_offset = golden_width_offset,
                                  width_tol = 0.5, highlight_fill = "FFFFFFCC", p_rows = NULL, publication_id = NULL) {
  mask <- golden_mask(mask)
  g <- golden_cell_styles(got_xlsx, got_sheet)
  w <- golden_cell_styles(want_xlsx, want_sheet)
  gl <- golden_sheet_layout(got_xlsx, got_sheet)
  wl <- golden_sheet_layout(want_xlsx, want_sheet)
  if (!is.null(publication_id)) {
    parts <- golden_publication_styles(g, w, gl, wl, publication_id)
    g <- parts$g; w <- parts$w; gl <- parts$gl; wl <- parts$wl
  }
  why <- character()
  if (!identical(gl$merges, wl$merges)) {
    why <- c(why, sprintf("merges: [%s] vs [%s]", paste(setdiff(gl$merges, wl$merges), collapse = " "),
                          paste(setdiff(wl$merges, gl$merges), collapse = " ")))
  }
  skip <- golden_merge_nonanchors(wl$merges)
  heads <- golden_mask_headers[intersect(mask, names(golden_mask_headers))]
  masked_cols <- unique(w$col[w$value %in% heads & w$row <= 3L])
  p_cols <- unique(w$col[w$value == "p-value" & w$row <= 3L])
  body_start <- 4L
  addr <- union(w$address[!w$address %in% skip], g$address[!g$address %in% skip])
  gi <- match(addr, g$address)
  wi <- match(addr, w$address)
  for (k in seq_along(addr)) {
    if (is.na(gi[k]) || is.na(wi[k])) {
      # A cell present on one side only must be blank and unstyled on that side.
      present <- if (is.na(gi[k])) w[wi[k], ] else g[gi[k], ]
      styled <- isTRUE(present$bold) || isTRUE(present$italic) || nzchar(present$fill) ||
        any(!is.na(unlist(present[c("border_top", "border_bottom", "border_left", "border_right")])))
      if (nzchar(present$value) || styled) {
        why <- c(why, sprintf("%s: present on one side only", addr[k]))
      }
      next
    }
    gr <- g[gi[k], ]
    wr <- w[wi[k], ]
    attrs <- golden_style_attrs
    bi <- wr$row - body_start + 1L
    row_p_masked <- is.null(p_rows) || bi < 1L || bi > length(p_rows) || p_rows[bi]
    col_masked <- wr$col %in% masked_cols && (!(wr$col %in% p_cols) || row_p_masked)
    if (col_masked && wr$row >= body_start && !golden_suppressed(gr$value) && !golden_suppressed(wr$value)) {
      attrs <- setdiff(attrs, "value")
      if (nzchar(gr$value) != nzchar(wr$value)) why <- c(why, sprintf("%s: masked blank pattern", addr[k]))
    }
    if ("pstyle" %in% mask && row_p_masked) {
      if (wr$col %in% p_cols && wr$row >= body_start) attrs <- setdiff(attrs, "bold")
      if (identical(gr$fill, highlight_fill) || identical(wr$fill, highlight_fill)) attrs <- setdiff(attrs, "fill")
    }
    for (a in attrs) {
      gv <- gr[[a]]
      wv <- wr[[a]]
      if (!identical(is.na(gv), is.na(wv)) || (!is.na(gv) && !identical(gv, wv))) {
        why <- c(why, sprintf("%s %s: '%s' vs '%s'", addr[k], a, gv, wv))
      }
    }
  }
  hh <- merge(gl$heights, wl$heights, by = "row", all = TRUE, suffixes = c(".got", ".want"))
  bad <- is.na(hh$height.got) | is.na(hh$height.want) | abs(hh$height.got - hh$height.want) > 1e-6
  if (any(bad, na.rm = TRUE)) {
    why <- c(why, sprintf("row %d height: %s vs %s", hh$row[bad], hh$height.got[bad], hh$height.want[bad]))
  }
  # Masked columns (Test, Statistic) size from the masked text, so their
  # widths are not compared; p-value and SMD widths are fixed and stay checked.
  used <- setdiff(sort(unique(w$col)), setdiff(masked_cols, p_cols))
  gw <- gl$widths$width[match(used, gl$widths$col)] - got_width_offset
  ww <- wl$widths$width[match(used, wl$widths$col)] - want_width_offset
  badw <- is.na(gw) != is.na(ww) | (!is.na(gw) & !is.na(ww) & abs(gw - ww) > width_tol)
  if (any(badw)) {
    why <- c(why, sprintf("col %s width: %s vs %s", golden_col_letters(used[badw]),
                          round(gw[badw], 3), round(ww[badw], 3)))
  }
  why
}

expect_styles_match <- function(xlsx, sheet, id, mask = NULL, got_width_offset = 0, tt = NULL) {
  sc <- golden_scenario(id)
  mask <- if (is.null(mask)) sc$mask else mask
  p_rows <- if (!is.null(tt$rows$vtype)) golden_p_masked_rows(tt)
  why <- golden_compare_styles(xlsx, sheet, golden_book(id), id,
                               mask = mask, got_width_offset = got_width_offset, p_rows = p_rows, publication_id = id)
  if (length(why)) {
    testthat::fail(paste0("styles ", id, ":\n", paste(utils::head(why, 12L), collapse = "\n")))
  } else {
    testthat::succeed()
  }
  invisible(why)
}

# ---------------------------------------------------------------------------
# Scenario runner

# Relative tolerance for an exact scenario's r(table) (Phase 4 review P2-8).
# r(table) holds fitted estimates, and Stata's iterative ML commands stop at
# their default convergence tolerance: logit/logistic/probit/cloglog and
# nbreg fits sit up to ~9e-9 (relative) from the MLE (refitting R01's
# logistic with tolerance(1e-14) ltolerance(1e-14) nrtolerance(1e-14) moves
# Female sex from .99327891475700325 to .99327891357652287, which R's glm()
# reproduces to 3e-16), so scenarios whose Stata setup runs one compare
# r(table) at 2e-8. Everything else (regress, stcox, poisson, glm, and every
# table1_tc scenario) is compared at 1e-9, the harness default.
# Per-scenario overrides, each with its reason:
golden_table_tol_override <- c(
  # cloglog: R's glm() stops when the relative deviance change is below
  # epsilon, and near the optimum the deviance moves with the square of the
  # coefficient error, so even epsilon = 1e-14 leaves the non-canonical
  # cloglog fit ~6e-8 from the MLE Stata reaches (auto: _cons
  # 10.0969351173 vs 10.0969357428).
  R31 = 1e-7,
  # Gamma log link: the same deviance criterion leaves R's IRLS fit ~3e-9
  # from the MLE of Stata's tightly converged glm (auto: _cons
  # 8.2752392553 vs 8.2752392806).
  R33 = 1e-8,
  # stcox on 37,643 split records stops ~4e-9 from the partial-likelihood
  # maximum R's coxph() reaches (Treatment group HR 1.04801699129 vs
  # 1.04801699577; a tight R refit moves it by 1e-12); the unsplit stcox
  # goldens agree to 1e-14.
  R45 = 2e-8,
  # exp() of a coefficient near 500 (C2's overflow golden): its relative
  # error is the coefficient's absolute error, and Stata's logit stops
  # ~1e-4 from the MLE at that scale (1.24975e+216 vs 1.24965e+216).
  R57 = 1e-4,
  # C6 (tabtools 2.1.13): the nbreg model is intercept and dummies only, so
  # glm.nb's fitted means are the cell means exactly (Intercept 245/146 =
  # 1.67808219178) and nbreg stops 2.4e-8 short of them (1.67808215165;
  # lnalpha 3.2e-8).
  R68 = 5e-8,
  R69 = 5e-8,
  R71 = 5e-8,
  # Task 5.15: Stata's logistic beside the clogit stops 1.4e-7 from the MLE
  # R's glm reaches at epsilon 1e-14 (Exposure score OR 1.51098187 vs
  # 1.51098208); the clogit column agrees to 1e-9.
  R76 = 2e-7
)
# Stored (non-table) tolerances of exact-mode scenarios whose cells match
# exactly but whose full-precision stored values carry a fit's convergence
# gap (C4 review F4): per scenario, never below 1e-9. Entries are added by
# the helper files that own the scenarios (helper-regtab-mi.R).
golden_stored_tol_override <- c(`_none` = 1e-9)
golden_stored_tol <- function(id) {
  if (id %in% names(golden_stored_tol_override)) golden_stored_tol_override[[id]] else 1e-9
}

golden_table_tol <- function(sc) {
  if (sc$id %in% names(golden_table_tol_override)) return(golden_table_tol_override[[sc$id]])
  if (grepl("\\b(logit|logistic|probit|cloglog|nbreg)\\b", sc$stata_setup)) 2e-8 else 1e-9
}

# Stored-result tolerances of the scenarios not in "exact" mode (phase 5,
# and R25q),
# per scenario, for r(table) and for every other stored number (Phase 5
# review P1-3: a blanket 1e-3 hid a wrong pseudo R-squared, mutation M56).
# Each is the smallest 1-2-5 step at or above the largest difference
# observed on 2026-09-25 (in the comment; absolute below 1, relative above,
# as golden_compare_stored() measures), never below the harness default
# 1e-9. The gaps are the R fits' convergence against Stata's: zeroinfl
# (R18, R25s) and the Fine-Gray coxph route (R20) ~1e-4, glmer's adaptive
# quadrature (R22) ~5e-6, geepack's default epsilon (R23, R25i) ~1e-6.
golden_stored_tol_tolerance <- list(
  R16 = c(table = 1e-7, other = 1e-9),   # table 7.4e-8, other 9e-16
  R17 = c(table = 5e-7, other = 1e-9),   # 3.1e-7, 5.6e-15
  R18 = c(table = 1e-4, other = 1e-9),   # 7.9e-5, 1.6e-10
  R19 = c(table = 1e-9, other = 1e-9),   # 4.3e-11, 0
  R20 = c(table = 1e-4, other = 1e-9),   # 7.4e-5, 0
  R21 = c(table = 5e-9, other = 5e-9),   # 2.3e-9, 2.4e-9
  R22 = c(table = 5e-6, other = 2e-6),   # 4.6e-6, 1.2e-6 (icc)
  R23 = c(table = 1e-6, other = 5e-9),   # 5.5e-7, 2.1e-9 (qic)
  R25f = c(table = 5e-9, other = 5e-9),  # 2.3e-9, 2.4e-9
  R25i = c(table = 1e-9, other = 1e-9),  # C5: fitted at geepack epsilon 1e-6 (the Race black upper bound
                                         # 2.53499946 sits on a rounding edge once exponentiated)
  R25p = c(table = 1e-7, other = 1e-9),  # 7.4e-8, 9e-16
  R25s = c(table = 1e-4, other = 1e-9),  # 7.9e-5, 1.6e-10
  # Phase 4: glm.nb stops at its iteration limit (theta ~ 2,600), so ll,
  # AIC and BIC sit ~3e-8 from nbreg's.
  R25q = c(table = 1e-8, other = 5e-8),  # 7.3e-9, 2.9e-8 (ll)
  # structure mode: the data-frame escape hatch built from Stata's own
  # r(table) (golden_tidy()), so its numbers agree to rounding.
  R25t = c(table = 1e-9, other = 1e-9),  # 2.5e-16, 2.6e-16
  # C2 (tabtools 2.1.11) goldens: the smallest 1-2-5 step that passed on
  # 2026-09-26, never below 1e-9. Convergence as above: pscl (R53, R55),
  # nnet at reltol 1e-14 (R54), lme4 vs Stata's mixed (R56, icc).
  R53 = c(table = 1e-4, other = 1e-9),
  R54 = c(table = 1e-8, other = 1e-9),
  R55 = c(table = 1e-5, other = 1e-9),
  R56 = c(table = 1e-5, other = 2e-7),
  # C5 (tabtools 2.1.12) goldens, measured 2026-09-26 as above: survreg
  # (R61, R62), polr at reltol 1e-14 (R63), nnet at reltol 1e-14 (R64),
  # pscl (R65).
  R61 = c(table = 2e-9, other = 1e-9),
  R62 = c(table = 1e-9, other = 1e-9),
  R63 = c(table = 5e-7, other = 1e-9),
  R64 = c(table = 2e-7, other = 1e-9),
  R65 = c(table = 1e-7, other = 1e-9),
  # C6 (tabtools 2.1.13) goldens, the Stata X1-X6 regressions, measured
  # 2026-09-27 as above: polr at reltol 1e-14 (R70), survreg (R72, R73).
  # R70: 1.1e-8 on x86_64; polr's BFGS stops 3.6e-7 away where long double
  # is double (macOS arm64 CI, 2026-10-01).
  R70 = c(table = 5e-7, other = 1e-9),   # 3.6e-7
  R72 = c(table = 2e-9, other = 1e-9),   # 1.3e-9
  R73 = c(table = 2e-9, other = 1e-9),   # 1.3e-9
  # Task 5.19 (nlme::lme as mixed), measured 2026-09-27 as above. The
  # likelihood is flat in the variance components, and lme's defaults, lme4
  # and a tightly converged lme agree with one another to ~1e-10 in ll
  # while Stata's mixed stops earlier: R81 var(_cons) lme 0.0246769, tight
  # lme 0.0246791, lmer 0.0246786, Stata 0.0246271 (ll equal to 1e-10);
  # R82 var(_cons[location]) 0.0564019 / 0.0564017 / 0.0564011 vs Stata
  # 0.0563933. R80 fits with niterEM = 200 (lme's default stops at ll
  # -838.45196 on the unscaled age slope, Stata at -838.45135, as lme4's
  # default optimizer does for R21's random slope).
  R78 = c(table = 1e-8, other = 1e-8),   # 9.1e-9, 9.4e-9 (icc)
  R79 = c(table = 5e-7, other = 5e-7),   # 2.8e-7, 2.9e-7 (icc)
  R80 = c(table = 5e-7, other = 5e-7),   # 4.3e-7, 3.3e-7 (icc)
  R81 = c(table = 5e-5, other = 5e-6),   # 5.0e-5 (var(_cons)), 2.1e-6 (icc)
  R82 = c(table = 1e-5, other = 2e-7)    # 8.6e-6, 1.3e-7 (icc)
)

# The sink stem pasted over @ID@ inside an r_call's string literals, with
# forward slashes: a Windows temp path (C:\Users\...) pasted as is would be
# parsed as escape sequences ("'\U' used without hex digits").
golden_code_path <- function(dir, id) {
  gsub("\\", "/", file.path(dir, id), fixed = TRUE)
}

# Run one golden scenario end to end: evaluate its r_call (with @ID@ sinks
# redirected to a temp dir), then compare cells, sinks, console, stored
# results, and xlsx styling. Skipped until its phase is done.
run_golden_scenario <- function(id, patch = NULL) {
  sc <- golden_scenario(id)
  if (!golden_scenario_live(id, sc$phase)) testthat::skip(paste("Phase", sc$phase))
  if (identical(sc$compare, "structure") && grepl("golden_tidy\\(", sc$r_call) &&
      !exists("golden_tidy", mode = "function")) {
    testthat::skip("no R model equivalent; data-frame escape hatch (task 5.8)")
  }
  out <- withr::local_tempdir()
  sinks <- golden_code_path(out, id)
  code <- gsub("@ID@", sinks, sc$r_call, fixed = TRUE)
  # Helpers (golden_fixture) live in the test environment, not globalenv,
  # under R CMD check.
  env <- new.env(parent = environment(golden_fixture))
  tt <- eval(parse(text = code), envir = env)
  expect_s3_class(tt, "tt_table")
  expect_identical(golden_check_derived(tt), character(), label = paste(id, "derived suppression cells"))
  # A documented, individually asserted divergence (test-golden-regtab.R)
  # may replace a cell before the comparators run.
  if (!is.null(patch)) tt <- if (identical(patch, golden_strip_smd_note)) patch(tt, id = id) else patch(tt)
  expect_cells_match(tt, id)
  expect_console_match(tt, id)
  # Sink paths and Markdown row counts exist only when a sink is written, and
  # the R call writes none (or writes to a temporary path): compare them via
  # the writers below instead.
  sink_fields <- c("xlsx", "sheet", "markdown", "csv", "markdown_rows", "markdown_cols")
  want <- golden_read_stored(id)
  fields <- setdiff(unique(want$name[want$kind != "meta"]), sink_fields)
  if (sc$compare == "exact") {
    # r(table) may need a looser, per-scenario tolerance: see
    # golden_table_tol(). Everything else is compared at 1e-9, unless
    # golden_stored_tol_override names the scenario (cells stay exact).
    expect_stored_match(tt, id, fields = setdiff(fields, "table"),
                        tolerance = golden_stored_tol(id))
    if ("table" %in% fields) expect_stored_match(tt, id, fields = "table", tolerance = golden_table_tol(sc))
  } else {
    tol <- golden_stored_tol_tolerance[[id]]
    if (is.null(tol)) stop("No stored tolerance for ", sc$compare, "-mode scenario ", id, " (golden_stored_tol_tolerance)")
    expect_stored_match(tt, id, fields = setdiff(fields, "table"), tolerance = tol[["other"]])
    if ("table" %in% fields) expect_stored_match(tt, id, fields = "table", tolerance = tol[["table"]])
  }
  xlsx <- file.path(out, paste0(sc$command, ".xlsx"))
  tabtools::tt_write_xlsx(tt, xlsx, sheet = id)
  expect_styles_match(xlsx, id, id, got_width_offset = golden_r_width_offset, tt = tt)
  # The workbook the r_call itself wrote (xlsx = "@ID@.xlsx"): covers the
  # argument plumbing (sheet, title, borderstyle) as well as the writer.
  own <- paste0(sinks, ".xlsx")
  if (file.exists(own)) {
    expect_styles_match(own, tt$stored$sheet %||% "Table 1", id, got_width_offset = golden_r_width_offset, tt = tt)
  }
  for (ext in c("csv", "md")) {
    path <- paste0(sinks, ".", ext)
    if (!file.exists(path)) {
      res <- switch(ext, csv = tabtools::tt_write_csv(tt, path), md = tabtools::tt_write_markdown(tt, path))
      if (ext == "md") {
        got_md <- list(markdown_rows = attr(res, "n_rows"), markdown_cols = attr(res, "n_cols"))
        expect_stored_match(got_md, id, fields = names(got_md))
      }
    } else if (ext == "md" && !is.null(tt$stored$markdown_rows)) {
      expect_stored_match(tt$stored[c("markdown_rows", "markdown_cols")], id,
                          fields = c("markdown_rows", "markdown_cols"))
    }
    expect_sink_match(path, id, ext, tt = tt)
  }
}

# Pending golden regeneration (2026-10-05): Stata tabtools 2.4.0 names the
# pair of a 3+ group SMD in the header ("SMD (A vs B)"), the console note
# and the footnote. R follows 2.4.0; the goldens are still 2.1.14's (bare
# "SMD" header, "Note: SMD computed for first two groups only (A vs B)",
# no footnote). The new form must appear exactly when 2.1.14 printed its
# note; it is then turned back into 2.1.14's so the rest of the table is
# compared. Delete this once the goldens come from 2.4.0
# (~/Stata-Dev/_take_action/2026-10-05-tabtools-smd-multigroup.md).
golden_strip_smd_note <- function(tt, id = NULL, native_grid = NULL, native_console = NULL) {
  if (!is.null(id)) {
    native_grid <- golden_read_cells(id)
    native_console <- golden_read_lines(golden_artifact_path(id, paste0(id, "_console.txt")))
  }
  if (is.null(native_grid) || is.null(native_console)) {
    stop("Legacy SMD translation requires explicit authentic native inputs.", call. = FALSE)
  }
  rx_old <- "^Note: SMD computed for first two groups only \\((.*) vs (.*)\\)$"
  old <- grep(rx_old, native_console, value = TRUE)
  actual_pre <- tt$meta$console_before %||% character()
  smd_col <- which(tt$cols$role == "smd")
  actual_new <- grep("^Note: SMD compares ", actual_pre, value = TRUE)
  if (!length(old)) {
    testthat::expect_identical(actual_new, character(), label = "no undeclared new SMD console note")
    if (length(smd_col)) testthat::expect_false(grepl("^SMD \\(", tt$header[[1]]$text[smd_col]))
    testthat::expect_false(any(startsWith(golden_fn_paragraphs(tt$footnote), "SMD compares ")))
    return(tt)
  }
  testthat::expect_length(old, 1L)
  pair <- sub(rx_old, "\\1 vs \\2", old)
  hdr <- which(apply(native_grid, 1L, function(row) any(trimws(row) == "SMD")))[1L]
  if (is.na(hdr)) stop("Native SMD note has no SMD header.", call. = FALSE)
  groups <- trimws(native_grid[hdr, -1L])
  groups <- sub("^(Crude|Weighted) ", "", groups)
  groups <- unique(setdiff(groups, c("", "Total", "SMD", "p-value", "Test", "Statistic")))
  note <- sprintf("SMD compares %s only (the first two of %d groups).", pair, length(groups))
  expected_pre <- paste("Note:", note)
  testthat::expect_identical(actual_new, expected_pre, label = "exact source-derived SMD console note")
  testthat::expect_length(smd_col, 1L)
  testthat::expect_identical(unname(tt$header[[1]]$text[smd_col]), paste0("SMD (", pair, ")"),
                             label = "exact source-derived SMD pair header")
  prior <- if (!is.null(id)) golden_publication_contract(id)$paragraphs else {
    tail <- native_grid[nrow(native_grid), 1L]
    if (startsWith(tail, "Counts below ")) tail else character()
  }
  testthat::expect_identical(golden_fn_paragraphs(tt$footnote), c(prior, note),
                             label = "complete independently expected footer before SMD translation")
  tt$meta$console_before[actual_pre == expected_pre] <- old
  tt$header[[1]]$text[smd_col] <- "SMD"
  tt$footnote <- paste(prior, collapse = " \\ ")
  tt
}
