library(testthat)
library(tabtools)

# These held oracles are generated by the root's authenticated isolated Stata17
# run of qa/stata/fitcount_v251_cases.do. This script executes no native process.
# Missing or damaged held artifacts are failures, never successful skips.
fitcount_qa_paths <- function() {
  root <- normalizePath(test_path(".."), mustWork = TRUE)
  list(root = root, tests = file.path(root, "tests", "testthat"),
       native = file.path(root, "tests", "testthat", "golden"))
}

test_that("installed fit-count APIs recover literal unweighted counts and immutable reuse", {
  d <- data.frame(y = c(1, 3, 2, 5, 4, 7), x = 1:6, ev = c(1, 0, 2, 0, 1, 0),
    pid = c("a", "a", "b", "c", "c", "d"), exposure = c(1, 2, 1, 3, 2, 4))
  fit <- lm(y ~ x, d, model = FALSE)
  record <- tt_fitcount(fit, "ev", "pid", "exposure", data = d, terms = TRUE)
  expect_identical(record$counts, c(obs = 6, events = 4, people = 4, people_ev = 3, exposure = 13))
  file <- withr::local_tempfile()
  saveRDS(record, file)
  rm(d)
  t <- regtab(fit, fitcounts = readRDS(file), stats = "obs events people exposure")
  expect_equal(unlist(t$stored[c("obs_1", "events_1", "people_1", "exposure_1")]),
    c(obs_1 = 6, events_1 = 4, people_1 = 4, exposure_1 = 13))
  changed <- fit; changed$fitted.values[1L] <- changed$fitted.values[1L] + 1e-12
  expect_error(regtab(changed, fitcounts = record), class = "tabtools_error_fitcount")
  expect_null(fit$model)
})

test_that("FC001 to FC003 authentic held native full grids and numeric returns match", {
  paths <- fitcount_qa_paths()
  env <- new.env(parent = environment())
  source(file.path(paths$tests, "helper-exact-num.R"), local = env)
  source(file.path(paths$tests, "helper-golden.R"), local = env)
  source(file.path(paths$tests, "helper-fitcount-native.R"), local = env)
  manifest <- utils::read.csv(file.path(paths$root, "qa", "data", "fitcount_v251_artifacts.csv"),
    stringsAsFactors = FALSE)
  expect_identical(sort(unique(manifest$id)), c("FC001", "FC002", "FC003"))
  expect_true(all(manifest$revision == "712044f83ce6dd7bb4ca4237f3f6ffbc8aea5129"))
  expect_true(all(manifest$tabtools_version == "2.5.1"))
  artifacts <- file.path(paths$native, manifest$file)
  expect_true(all(file.exists(artifacts)))
  expect_identical(unname(tools::md5sum(artifacts)), manifest$md5)
  scratch <- withr::local_tempdir(pattern = "fitcount-native-sinks-")
  for (id in c("FC001", "FC002", "FC003")) {
    paths_r <- list(xlsx = file.path(scratch, "regtab.xlsx"),
                    markdown = file.path(scratch, paste0(id, ".md")), sheet = id)
    t <- env$fitcount_native_case(id, sinks = paths_r)
    grid <- env$golden_read_cells_file(file.path(paths$native, paste0(id, ".csv")))
    expect_equal(nrow(env$golden_compare_cells(env$golden_as_cells(t), grid, mask = character(), mode = "exact")), 0L)
    native <- utils::read.csv(file.path(paths$native, paste0(id, "_stored.csv")),
      colClasses = "character", na.strings = character(), check.names = FALSE)
    expect_identical(native$value[native$name == "_golden_tabtools_version"], "2.5.1")
    # Execution destinations differ; validate native sink identities before
    # projecting only those literal paths to this fresh owned destination.
    expect_identical(native$value[native$name == "sheet"], id)
    expect_identical(basename(native$value[native$name == "xlsx"]), "regtab.xlsx")
    expect_identical(basename(native$value[native$name == "markdown"]), paste0(id, ".md"))
    for (field in c("xlsx", "markdown")) native$value[native$name == field] <- paths_r[[field]]
    native_projection <- t$stored
    if (id == "FC002") {
      # D2 deliberately retains all analytical coefficients in R. The native
      # r(table) contains only the four publication-eligible coefficients.
      # Assert the six raw values independently before comparing that complete
      # publication matrix with the held native four-row return.
      raw_names <- c("__1", "__3", "x", "1_g_x", "3_g_x", "Intercept")
      raw_values <- c(-22/21, 34/21, 36/35, -4/35, -4/35, 38/7)
      raw_contract <- function(value) {
        identical(dim(value), c(6L, 1L)) &&
          identical(dimnames(value), list(raw_names, "c1")) &&
          all(is.finite(value)) && max(abs(as.numeric(value) - raw_values)) < 1e-12
      }
      expect_true(raw_contract(t$stored$table))
      expect_identical(dim(t$stored$publication_table), c(4L, 1L))
      expect_identical(dimnames(t$stored$publication_table),
        list(c("__3", "x", "3_g_x", "Intercept"), "c1"))
      expect_equal(as.numeric(t$stored$publication_table),
        c(34/21, 36/35, -4/35, 38/7), tolerance = 1e-12)
      corrupted_raw <- t$stored$table
      corrupted_raw[1L, 1L] <- corrupted_raw[1L, 1L] + 1
      expect_false(raw_contract(corrupted_raw))
      native_projection$table <- t$stored$publication_table
      corrupted_publication <- native_projection
      corrupted_publication$table[1L, 1L] <- corrupted_publication$table[1L, 1L] + 1
      expect_gt(length(env$golden_compare_stored(corrupted_publication, native,
        mask = character())), 0L)
      expect_identical(t$stored$table_role, "raw_analytical")
    }
    expect_identical(env$golden_compare_stored(native_projection, native,
      mask = character()), character())
    if (id == "FC002") {
      expect_identical(t$stored$smallcells, list(threshold = 7L, mode = "primary", n_masked = 2L, n_linked = 0L))
      expect_identical(t$meta$regtab_rows$status[t$meta$regtab_rows$key == "2.g#c.x"], "ref")
    }
    if (id == "FC003") {
      expect_equal(t$stored$N_stats_masked, 24)
      expect_equal(t$stored$N_stats_linked, 24)
      parts <- t$meta$regtab_stats_provenance
      expect_identical(parts$model_index[parts$part_name == "index"], 1:12)
      expect_identical(parts$raw_value[parts$part_name == "index"], as.numeric(1:12))
    }
    damaged <- t$stored
    damaged$N_models <- t$stored$N_models + 1L
    expect_gt(length(env$golden_compare_stored(damaged, native)), 0L)
  }
})

test_that("resolved session sinks carry protected literal cells and preserve raw labels", {
  paths <- fitcount_qa_paths()
  env <- new.env(parent = environment())
  source(file.path(paths$tests, "helper-fitcount-native.R"), local = env)
  d <- data.frame(y = c(1, 3, 2, 5, 4, 7), x = 1:6)
  fit <- lm(y ~ x, d)
  directory <- withr::local_tempdir(pattern = "fitcount-sinks-")
  opts <- tabtools_options()
  withr::defer({ tabtools_options(clear = TRUE); if (length(opts)) do.call(tabtools_options, opts) })
  xlsx <- file.path(directory, "sink.xlsx"); md <- file.path(directory, "sink.md")
  tabtools_options(workbook = xlsx, markdown = md)
  t <- regtab(fit, sheet = "Counts", stats = list(list(name = "ev", mincell = 5, maskwith = "zero"),
    list(name = "zero")), stat_values = list(list(ev = 3, zero = 0)))
  expect_identical(t$body[t$rows$key == "stat:e(ev)", 2L], "<5")
  expect_identical(t$body[t$rows$key == "stat:e(zero)", 2L], "\u2013")
  expect_true(file.exists(xlsx)); expect_true(file.exists(md))
  expect_true("Counts" %in% openxlsx2::wb_get_sheet_names(openxlsx2::wb_load(xlsx)))
  expect_true(any(grepl("<5", readLines(md), fixed = TRUE)))
  expect_identical(t$stored$table_role, "raw_analytical")
  expect_identical(t$stored$e_ev_1, 3)
  expect_identical(t$stored$e_zero_1, 0)
})

for (converter in c("gt", "flextable", "gtsummary", "tinytable")) local({
  package <- converter
  test_that(paste("installed", package, "carries rich-statistic protection"), {
    expect_true(requireNamespace(package, quietly = TRUE))
    if (!requireNamespace(package, quietly = TRUE)) stop("Required converter unavailable.")
    fit <- lm(y ~ x, data.frame(y = c(1, 3, 2, 5, 4, 7), x = 1:6))
    t <- regtab(fit, stats = list(list(name = "ev", mincell = 5, maskwith = "zero"), list(name = "zero")),
      stat_values = list(list(ev = 3, zero = 0)))
    if (package == "gt") {
      object <- tt_as_gt(t)
      expect_true(any(as.matrix(object[["_data"]]) == "<5"))
      expect_true(any(as.matrix(object[["_data"]]) == "\u2013"))
    } else if (package == "flextable") {
      object <- flextable::as_flextable(t)
      expect_true(any(as.matrix(object$body$dataset) == "<5"))
      expect_true(any(as.matrix(object$body$dataset) == "\u2013"))
    } else if (package == "gtsummary") {
      object <- tt_as_gtsummary(t)
      expect_true(any(as.matrix(object$table_body) == "<5"))
      expect_true(any(as.matrix(object$table_body) == "\u2013"))
    } else {
      object <- tt_as_tinytable(t)
      expect_true(any(as.matrix(methods::slot(object, "data")) == "<5"))
      expect_true(any(as.matrix(methods::slot(object, "data")) == "\u2013"))
    }
  })
})
